name: Test

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Out'
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential \
          pkg-config \
          autoconf \
          libtool \
          wget \
          sqlite3 libsqlite3-dev libjq-dev

      - name: Build extension
        run: |
          make all

      - name: Run tests
        run: |
          make test
